# Generated by Django 4.1.3 on 2022-11-10 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medium', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name='title',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='title',
            name='date',
            field=models.DateField(verbose_name='Release Date'),
        ),
    ]
